version: '2'
services:
  soa-externe:
    build: .
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./named.conf:/etc/bind/named.conf
      - ./db.wood.domaineprojetadmin.ovh:/etc/bind/db.wood.domaineprojetadmin.ovh
    container_name: container_DNS